### ISSUE TITLE
rename repo to: `dbt-layer` or `dbt-layerai`?

### ISSUE THREAD

**Issue by dataders** [layerai/dbt-layer#64]
we have an unwritten standard on adapter names: `dbt-$ADAPTERNAME`. Now might be a great time to switch the name before too many take dependencies on this?

**Comment by volkangurel** [comment]
thanks for the heads up! i think it would make sense to rename to `dbt-layer`, let me check with the team and make the change if there are no objections

**Comment by volkangurel** [comment]
Done!
